## <font color='blue'>Curso de Extensão: Análise de Dados em Python - Aula 2 - Numpy</font>

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 12.5 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
#Cria um numpy array
x = np.array([10,20,30])
print(x)
y = np.array([40,50,60])
print(y)
#Soma elementos de dois np arrays
x+y

[10 20 30]
[40 50 60]


array([50, 70, 90])

In [3]:
#Cria np array no formato de matriz
x = np.array([[10,20],[30,40]])
print(x)

[[10 20]
 [30 40]]


In [4]:
#Soma todos os elementos da matriz
print("Soma todos: ",np.sum(x))
#Soma por coluna
print("Soma por coluna: ", np.sum(x,axis=0))
#Soma por linha
print("Soma por linha: ", np.sum(x,axis=1))

Soma todos:  100
Soma por coluna:  [40 60]
Soma por linha:  [30 70]


In [5]:
#Gera um vetor de números de 5 a 101, intercalando de 5 em 5.
z_arr = np.arange(5,101,5)
print(z_arr)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [5]:
#Gera um numpy array com números de 0 a 20, com dimensão 5 x 4 (5 linhas e 4 colunas)
y=np.arange(20).reshape(5,4)
print(y)                 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [6]:
#Aplica um reshape em y para gerar 5 arrays no formato 2x2. 
#Sintaxe: reshape(quantity of arrays,line,column)
y=y.reshape(5,2,2)
print(y)     

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [7]:
print("Shape de y: ", y.shape)
print("Dimensão de y: ", y.ndim)
print("Tamanho de y: ", y.size)
print("Tipo dos dados: ", y.dtype)

Shape de y:  (5, 2, 2)
Dimensão de y:  3
Tamanho de y:  20
Tipo dos dados:  int32


In [8]:
#Gera um np array 5x5 contedo o valor 0
zeros = np.zeros((5,5)) #zeros
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#Gera um np array 1x2 contedo o valor 1
ones = np.ones((10,2)) 
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
#Gera um np array 2x2 contendo o número 3 
equals = np.full((2000,2),3) #replica
print(equals)

[[3 3]
 [3 3]
 [3 3]
 ...
 [3 3]
 [3 3]
 [3 3]]


In [11]:
#Gera um np array 6x6 contendo apenas números randômicos
randons = np.around(np.random.random((6,6)),2)
print(randons)

[[0.44 0.31 0.12 0.66 0.87 0.17]
 [0.98 0.84 0.27 0.22 0.32 0.29]
 [0.86 0.8  0.45 0.08 0.94 0.38]
 [0.48 0.24 0.71 0.82 0.48 0.83]
 [0.97 0.   0.56 0.34 0.22 0.88]
 [0.27 0.41 0.46 0.69 0.19 0.64]]


In [12]:
#Cria um np array
a = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [32]:
#Slice the np array: pega os dados até a linha 3 (excludente) e as colunas de 1 a 3 (excludente)
b=a[1:3,1:3]
print("Array b")
print(b)

Array b
[[ 60  70]
 [100 110]]


In [35]:
print("Array a")
print(a[0,1])
b[0,0]=77
print("Array b")
print(b)
print("Array a")
print(a[2,1])

Array a
20
Array b
[[ 77  70]
 [100 110]]
Array a
100
